services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "6001:8000"
    environment:
      - CONFIG_PATH=/etc/gaodcore/config.yaml
      - POSTGRESQL_HOST=postgres-gaodcore
      - POSTGRESQL_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER:-gaodcore}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-gaodcore}
      - POSTGRES_DB=${POSTGRES_DB:-ga_od_core}
      - "API_BASE_URL=https://desopendata.aragon.es/GA_OD_Core"
      - "DJANGO_LOG_LEVEL=${DJANGO_LOG_LEVEL:-INFO}"
    configs:
      - source: gaodcore-config
        target: /etc/gaodcore/config.yaml
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - infraestructura_opendata
    healthcheck:
      test: [ "CMD-SHELL", "curl -I -f http://localhost:8000/GA_OD_Core/ui/" ]
      interval: 20s
      timeout: 5s
      retries: 5

  postgres:
    build:
      context: docker/postgres
      dockerfile: Dockerfile
    container_name: postgres-gaodcore
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    environment:
      - TZ=Europe/Madrid
      - POSTGRES_USER=${POSTGRES_USER:-gaodcore}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-gaodcore}
      - POSTGRES_DB=${POSTGRES_DB:-ga_od_core}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - infraestructura_opendata

configs:
  gaodcore-config:
    file: config.yaml

volumes:
  postgres_storage:

networks:
  infraestructura_opendata:
    external: true
